### ISSUE TITLE
Reproduce and fix crash regarding the Recycler View

### ISSUE THREAD

**Issue by Wojtechnology** [Wojtechnology/Sunami#16]
From Google play crash reports:

``` java
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$LayoutManager.onAddFocusables(android.support.v7.widget.RecyclerView, java.util.ArrayList, int, int)' on a null object reference
```

Crash occurring on startup for some devices.

**Comment by Wojtechnology** [comment]
https://github.com/ManuelPeinado/FadingActionBar/issues/65

**Comment by Wojtechnology** [comment]
Might have solved problem, still need to check with user who had error.

**Comment by Wojtechnology** [comment]
Fixed by rearranging `setLayoutManager()` with `setAdapter()`.

**Comment by jessexugitlab** [comment]
how to fix this problem?please tell me more details
